name: CI

on:
  push:
  pull_request:
      branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cc: [clang, gcc]
    steps:
      - uses: actions/checkout@v6
        with:
            submodules: true
      - uses: actions/setup-python@v6
        with:
            python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libarchive-dev
          pip3 install meson ninja
      - name: Build
        run: |
          meson build -Dengine=asbestos -Dkernel=ish
          ninja -C build
        env:
          CC: ${{matrix.cc}}
      - name: Test
        run: ninja -C build test

  build-mac:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v6
        with:
            submodules: true
      - name: Install dependencies
        run: |
          brew install llvm lld ninja libarchive meson
      - name: Build
        run: xcodebuild -project iSH.xcodeproj -scheme iSH-ARM64 -arch arm64 -sdk iphoneos CODE_SIGNING_ALLOWED=NO
